apiVersion: apps/v1
kind: Deployment
metadata:
    name: linkasa-frontend
spec:
    replicas: 2
    selector:
        matchLabels:
            app: linkasa-frontend
    template:
        metadata:
            labels:
                app: linkasa-frontend
        spec:
            containers:
                - name: linkasa-frontend
                  image: techtestntdarrenkent.azurecr.io/linkasa_frontend:latest
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: linkasa-frontend-service
spec:
    selector:
        app: linkasa-frontend
    ports:
        - port: 8080
          targetPort: 8080
    type: LoadBalancer
